### ISSUE TITLE
blockly-compressed.js issue

### ISSUE THREAD

**Issue by i8beef** [kumavis/node-blockly#3]
With the version that I pulled down from NPM, there is a mispelled "funcion" in the blockly-compresed.js file. It would not run until I changed that to be "function".

**Comment by i8beef** [comment]
Nevermind, you aren't the maintainer of the NPM package.

**Comment by kumavis** [comment]
@i8beef actually i am maintainer of the npm package `blockly` but it is very outdated.

please see these relevant issues on the google/blockly repo:
https://github.com/google/blockly/issues/177
https://github.com/google/blockly/pull/136
